apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-with-quota
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: cli-eksrauto-549357039
  resourceQuotas:
    ephemeralStorageLimits: 100Mi
